# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Official Himali Samay Website - Nepali Brand Watches
company: Himali Samay Enterprises
location: Ason - 25, Kathmandu, Nepal
keywords: nepal watch,nepali watch,nepali watches,himali,samay,himali samay,nepal wooden watch,nepali wooden watch,nepal watches,wooden watch,beautiful watch,nepal beautiful watch,stylish watch,slylish watch nepal,branded watch,branded watch nepal,stylish watch,stylish watches
email: himalisamay@gmail.com
phone: +977-9841633739
country: Nepal
facebook_url: https://facebook.com/himalisamay
instagram_url: https://instagram.com/himalisamay
# baseurl: "himalisamay.com" # the subpath of your site, e.g. /blog
url: "https://himalisamay.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  himalitech

# Build settings
intro_title: Beautifully Crafted Nepali Brand Watches
intro_description: >-
  Himali Samay watches are sleek and classic with a slight Nepali touch. Every components is assembled with scrupulous attention to detail. A truly Nepali look &amp; feel watch to represent Nepal locally &amp; globally. 

designed_by: Puru Tuladhar
designed_by_url: https://tuladhar.github.io

  # theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
